scrapeConfig:
  url: "https://www.thewhiskyexchange.com/p/85794/bunnahabhain-12-year-old-cask-strength-2025-release"
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  priceSelector: ".product-action__price"